[package]

name = "geohash"
version = "0.0.1"
authors = ["Xu Chen <windoze.net@gmail.com>"]

description = "A Rust GeoHash Library"
license = "MIT"

repository = "https://github.com/windoze/geohash-rust"
